server:
  port: 8091
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      
  application:
   name : spring-cloud-eureka-client-dept
   
  main:
    allow-bean-definition-overriding: true
   
eureka:
 client:
   service-url:
     defaultZone : ${EUREKA_URI:http://localhost:8761/eureka}

 instance:
   prefer-ip-address: true
    

  
